<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(DotnetVersion)</TargetFramework>
    <AssemblyName>Xilium.CefGlue.BrowserProcess</AssemblyName>
    <RootNamespace>Xilium.CefGlue.BrowserProcess</RootNamespace>
    <RuntimeIdentifiers>osx-x64;osx-arm64;win-x64;win-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishCommonConfig>Configuration=$(Configuration);Platform=$(Platform);TargetFramework=$(TargetFramework);IsPublishing=True;PublishTrimmed=True;SelfContained=True;RuntimeIdentifier=</PublishCommonConfig>
    <IsEditbinEnabled>True</IsEditbinEnabled>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOSPlatform('Windows'))">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOSPlatform('Linux'))">linux-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOSPlatform('OSX'))">osx-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <Import Project="$(ProjectDir)..\CefGlue.Packages.props" />

  <ItemGroup>
    <None Remove="ObjectBinding\CefGlueGlobalScript.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CefGlue.BrowserProcess.Core\CefGlue.BrowserProcess.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\CefGlue.Demo.WPF\StackDebug.cs" Link="StackDebug.cs" />
  </ItemGroup>

  <Import Project="$(ProjectDir)..\CefGlue.Common\build\CefGlue.Common.targets" />

  <Target Name="PublishApp" AfterTargets="AfterBuild" Condition="'$(_AssemblyTimestampBeforeCompile)' != '$(_AssemblyTimestampAfterCompile)' and '$(IsPublishing)' != 'True'">
   
    <Message Text="Publishing CefGlue.BrowserProcess for $(RuntimeIdentifier) ..." Importance="High" />
    <MSBuild Projects="CefGlue.BrowserProcess.csproj" Targets="Publish" Properties="$(PublishCommonConfig)$(RuntimeIdentifier)" />
  </Target>
</Project>
