<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)</TargetFramework>
    <RootNamespace>Xilium.CefGlue.Avalonia</RootNamespace>
    <AssemblyName>Xilium.CefGlue.Avalonia</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug_WindowlessRender'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\CefGlue.Common\BaseCefBrowser.cs" Link="Common\BaseCefBrowser.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference PrivateAssets="all" Include="Avalonia" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="System.Reactive.Linq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CefGlue.BrowserProcess.Core\CefGlue.BrowserProcess.Core.csproj" />
    <ProjectReference Include="..\CefGlue.Common\CefGlue.Common.csproj" PrivateAssets="none" />
    <ProjectReference Include="..\CefGlue\CefGlue.csproj" PrivateAssets="all" />
  </ItemGroup>

</Project>
