//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "148.0.9+g0d9d52a+chromium-148.0.7778.180";
        public const int CEF_VERSION_MAJOR = 148;
        public const int CEF_COMMIT_NUMBER = 3519;
        public const string CEF_COMMIT_HASH = "0d9d52a65c74c729e568ebf8506141a1e754eaeb";
        
        public const int CHROME_VERSION_MAJOR = 148;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 7778;
        public const int CHROME_VERSION_PATCH = 180;
        
        public const int CEF_API_VERSION = 14800;
        public const string CEF_API_HASH_PLATFORM_WIN = "a9fddb1f86f1fc427a6eee19a370dbedb14468cb";
        public const string CEF_API_HASH_PLATFORM_MACOS = "c4a25b0e7f0beb51b9f5db9fb75904d11dd856a1";
        public const string CEF_API_HASH_PLATFORM_LINUX = "aa2de54c143e9ffffd183177f14c325820b5916a";
    }
}
