<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <AssemblyName>Xilium.CefGlue.BrowserProcess.Core</AssemblyName>
        <RootNamespace>Xilium.CefGlue.BrowserProcess</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="ObjectBinding\CefGlueGlobalScript.js" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\CefGlue.Common.Shared\CefGlue.Common.Shared.csproj" />
        <ProjectReference Include="..\CefGlue\CefGlue.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="Xilium.CefGlue.BrowserProcess" />
    </ItemGroup>

</Project>
