<Project Sdk="Microsoft.NET.Sdk">
    
  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Xilium.CefGlue.WPF</RootNamespace>
    <AssemblyName>Xilium.CefGlue.WPF</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
    
  <ItemGroup>
    <Compile Include="..\CefGlue.Common\BaseCefBrowser.cs">
      <Link>Common\BaseCefBrowser.cs</Link>
    </Compile>
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\CefGlue.BrowserProcess.Core\CefGlue.BrowserProcess.Core.csproj" />
    <ProjectReference Include="..\CefGlue.Common\CefGlue.Common.csproj" PrivateAssets="none" />
    <ProjectReference Include="..\CefGlue\CefGlue.csproj" PrivateAssets="all" />
  </ItemGroup>
</Project>