using System;
using NUnit.Framework;
using Xilium.CefGlue.Common.Shared;

namespace CefGlue.Tests
{
    /// <summary>
    /// Round-trips <see cref="SharedRegion"/> within one process. That is not the case it exists
    /// for — it carries OSR frames between the browser and render processes — but the mapping,
    /// naming and lifetime rules are the same either way, and this is the half that can be tested
    /// without spawning CEF. Deliberately does not inherit <c>TestBase</c>, so no browser starts.
    /// </summary>
    public class SharedRegionTests
    {
        private static string UniqueName() => "CG_TEST_" + Guid.NewGuid().ToString("N").Substring(0, 8);

        [Test]
        public void OpenExisting_SeesWhatTheCreatorWrote()
        {
            var name = UniqueName();
            using var writer = SharedRegion.Create(name, 4096);
            unsafe
            {
                writer.Pointer[0] = 0xAB;
                writer.Pointer[4095] = 0xCD;
            }

            using var reader = SharedRegion.OpenExisting(name, 4096);

            Assert.That(reader, Is.Not.Null);
            Assert.That(reader.Length, Is.GreaterThanOrEqualTo(4096));
            unsafe
            {
                Assert.That(reader.Pointer[0], Is.EqualTo(0xAB));
                Assert.That(reader.Pointer[4095], Is.EqualTo(0xCD));
            }
        }

        [Test]
        public void OpenExisting_SeesLaterWrites_BecauseTheMappingIsShared()
        {
            var name = UniqueName();
            using var writer = SharedRegion.Create(name, 4096);
            using var reader = SharedRegion.OpenExisting(name, 4096);

            unsafe
            {
                // Written AFTER the reader mapped it: the point of the persistent region is that
                // the reader keeps one mapping and sees every subsequent frame through it.
                writer.Pointer[128] = 0x42;
                Assert.That(reader.Pointer[128], Is.EqualTo(0x42));
            }
        }

        [Test]
        public void OpenExisting_ReturnsNullForAnUnknownName()
        {
            Assert.That(SharedRegion.OpenExisting(UniqueName(), 4096), Is.Null);
        }

        // The opener maps what the caller asks for, because macOS will not report a shared-memory
        // object's size. Asking for more than the creator made must therefore fail to open, rather
        // than hand back a mapping whose tail is not backed by anything.
        [Test]
        public void OpenExisting_ReturnsNull_WhenTheRegionIsSmallerThanTheCallerNeeds()
        {
            var name = UniqueName();
            using var writer = SharedRegion.Create(name, 64 * 1024);

            // Far enough past the creator's size to clear any rounding the platform applies —
            // macOS rounds a region up to a page, Windows to the 64K allocation granularity.
            Assert.That(SharedRegion.OpenExisting(name, 4 * 1024 * 1024), Is.Null);
        }

        [Test]
        public void OpenExisting_MapsAtLeastWhatTheCallerAskedFor()
        {
            var name = UniqueName();
            using var writer = SharedRegion.Create(name, 64 * 1024);
            unsafe { writer.Pointer[64 * 1024 - 1] = 0x7F; }

            using var reader = SharedRegion.OpenExisting(name, 64 * 1024);

            Assert.That(reader, Is.Not.Null);
            Assert.That(reader.Length, Is.GreaterThanOrEqualTo(64 * 1024));
            unsafe { Assert.That(reader.Pointer[64 * 1024 - 1], Is.EqualTo(0x7F)); }
        }

        [Test]
        public void OpenExisting_ReturnsNullRatherThanThrowing_ForANonPositiveSize()
        {
            var name = UniqueName();
            using var writer = SharedRegion.Create(name, 4096);

            Assert.That(SharedRegion.OpenExisting(name, 0), Is.Null);
            Assert.That(SharedRegion.OpenExisting(name, -1), Is.Null);
        }

        [Test]
        public void OpenExisting_ReturnsNullRatherThanThrowing_ForAnEmptyName()
        {
            // A frame notify racing a resize can carry a stale name; at frame rate the difference
            // between null and an exception is the whole error budget.
            Assert.That(SharedRegion.OpenExisting(null, 4096), Is.Null);
            Assert.That(SharedRegion.OpenExisting("", 4096), Is.Null);
        }

        [Test]
        public void Create_RejectsANonPositiveSize()
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => SharedRegion.Create(UniqueName(), 0));
        }

        [Test]
        public void Name_IsCarriedThrough_SoAConsumerCanTellRegionsApart()
        {
            var name = UniqueName();
            using var region = SharedRegion.Create(name, 4096);

            Assert.That(region.Name, Is.EqualTo(name));
        }

        // macOS caps a POSIX shm name at 31 characters including the leading slash, and the OSR
        // names are generated by the embedder. A name that fits Windows but not macOS must fail
        // loudly on the platform that cannot take it, rather than silently not sharing.
        [Test]
        public void Create_RejectsANameTooLongForPosix_OnPosix()
        {
            if (OperatingSystem.IsWindows()) Assert.Ignore("POSIX name limit does not apply to Windows named maps");

            var tooLong = new string('x', SharedRegion.MaxPosixNameLength + 1);
            Assert.Throws<ArgumentException>(() => SharedRegion.Create(tooLong, 4096));
        }
    }
}
