using System;
using System.IO.MemoryMappedFiles;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

namespace Xilium.CefGlue.Common.Shared
{
    /// <summary>
    /// A named, cross-process shared-memory region that outlives a single frame: created once by
    /// the browser process, opened once by the render process, and written/read many times.
    ///
    /// <para><b>Why this exists.</b> The per-frame path (<c>CefSharedProcessMessageBuilder</c>)
    /// allocates a fresh region for every frame, and a fresh region is demand-zero: the OS zeroes
    /// and maps each page as the writer first touches it. For an OSR frame that is megabytes of
    /// first-touch faults on every paint — measured at 17–22ms per 4.53 MP frame on Windows and
    /// ~10.9ms on Apple Silicon, against ~2.5ms for the pixel work itself. A region that lives
    /// across frames pays that once instead of thirty times a second.</para>
    ///
    /// <para><b>Why not just MemoryMappedFile.</b> .NET's named maps
    /// (<see cref="MemoryMappedFile.CreateNew(string,long)"/> /
    /// <see cref="MemoryMappedFile.OpenExisting(string)"/>) are Windows-only, so the persistent
    /// path used to be a Windows-only escape hatch. On Unix this uses POSIX shared memory
    /// (<c>shm_open</c> + <c>mmap</c>), which is the same primitive with a different spelling.</para>
    /// </summary>
    public sealed unsafe class SharedRegion : IDisposable
    {
        /// <summary>
        /// macOS caps a POSIX shared-memory name at <c>PSHMNAMLEN</c> (31) INCLUDING the leading
        /// slash, and silently fails past it. Names are generated by the embedder, so this is
        /// checked rather than assumed.
        /// </summary>
        public const int MaxPosixNameLength = 31;

        private readonly MemoryMappedFile _mmf;
        private readonly MemoryMappedViewAccessor _view;
        private readonly IntPtr _posixAddress;
        private readonly nuint _posixLength;
        private readonly bool _posixOwner;
        private bool _disposed;

        private SharedRegion(string name, byte* pointer, long length,
            MemoryMappedFile mmf, MemoryMappedViewAccessor view,
            IntPtr posixAddress, nuint posixLength, bool posixOwner)
        {
            Name = name;
            Pointer = pointer;
            Length = length;
            _mmf = mmf;
            _view = view;
            _posixAddress = posixAddress;
            _posixLength = posixLength;
            _posixOwner = posixOwner;
        }

        /// <summary>The name both processes address this region by.</summary>
        public string Name { get; }

        /// <summary>Start of the mapping. Valid until <see cref="Dispose"/>.</summary>
        public byte* Pointer { get; }

        /// <summary>Mapped length in bytes.</summary>
        public long Length { get; }

        /// <summary>
        /// Create a region and own its lifetime. On Unix an existing region of the same name is
        /// replaced, so a stale one left by a crashed process cannot be inherited at the wrong size.
        /// </summary>
        public static SharedRegion Create(string name, long size)
        {
            if (string.IsNullOrEmpty(name)) throw new ArgumentException("name is required", nameof(name));
            if (size <= 0) throw new ArgumentOutOfRangeException(nameof(size));

            if (OperatingSystem.IsWindows()) return CreateWindows(name, size);
            return CreatePosix(name, size);
        }

        /// <summary>
        /// Open a region someone else created, read-only, or null when it does not exist. A caller
        /// racing a resize (the region is recreated under a new name) gets null rather than an
        /// exception — at frame rate that difference is the whole error budget.
        /// </summary>
        public static SharedRegion OpenExisting(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            return OperatingSystem.IsWindows() ? OpenWindows(name) : OpenPosix(name);
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;

            if (_view != null)
            {
                _view.SafeMemoryMappedViewHandle.ReleasePointer();
                _view.Dispose();
                _mmf?.Dispose();
                return;
            }

            if (_posixAddress != IntPtr.Zero) Posix.munmap(_posixAddress, _posixLength);
            // Only the creator unlinks: the name has to outlive a reader that is between frames.
            if (_posixOwner) Posix.shm_unlink(PosixName(Name));
        }

        // --- Windows ---

        [SupportedOSPlatform("windows")]
        private static SharedRegion CreateWindows(string name, long size)
        {
            var mmf = MemoryMappedFile.CreateNew(name, size);
            return MapWindows(name, mmf, size);
        }

        [SupportedOSPlatform("windows")]
        private static SharedRegion OpenWindows(string name)
        {
            MemoryMappedFile mmf;
            try { mmf = MemoryMappedFile.OpenExisting(name); }
            catch { return null; }
            return MapWindows(name, mmf, 0);
        }

        [SupportedOSPlatform("windows")]
        private static SharedRegion MapWindows(string name, MemoryMappedFile mmf, long size)
        {
            var view = mmf.CreateViewAccessor();
            byte* p = null;
            view.SafeMemoryMappedViewHandle.AcquirePointer(ref p);
            long length = size > 0 ? size : (long)view.SafeMemoryMappedViewHandle.ByteLength;
            return new SharedRegion(name, p, length, mmf, view, IntPtr.Zero, 0, false);
        }

        // --- POSIX ---

        /// <summary>POSIX shm names are absolute-path-like; the embedder's plain name is adapted.</summary>
        private static string PosixName(string name)
        {
            var posix = name.StartsWith("/", StringComparison.Ordinal) ? name : "/" + name;
            if (posix.Length > MaxPosixNameLength)
                throw new ArgumentException(
                    $"shared-memory name '{posix}' exceeds the {MaxPosixNameLength}-character POSIX limit", nameof(name));
            return posix;
        }

        private static SharedRegion CreatePosix(string name, long size)
        {
            var posixName = PosixName(name);
            // A region left behind by a crashed process would otherwise be opened at its old size.
            Posix.shm_unlink(posixName);

            int fd = Posix.shm_open(posixName, Posix.O_RDWR | Posix.O_CREAT | Posix.O_EXCL, 0b110_000_000 /* 0600 */);
            if (fd < 0) throw new InvalidOperationException($"shm_open('{posixName}') failed: errno {Marshal.GetLastWin32Error()}");

            try
            {
                // macOS allows ftruncate on a shm object exactly once, which is why a resize
                // creates a new name (generation) rather than growing this one.
                if (Posix.ftruncate(fd, size) != 0)
                    throw new InvalidOperationException($"ftruncate('{posixName}', {size}) failed: errno {Marshal.GetLastWin32Error()}");

                var addr = Posix.mmap(IntPtr.Zero, (nuint)size, Posix.PROT_READ | Posix.PROT_WRITE, Posix.MAP_SHARED, fd, 0);
                if (addr == Posix.MAP_FAILED)
                    throw new InvalidOperationException($"mmap('{posixName}', {size}) failed: errno {Marshal.GetLastWin32Error()}");

                return new SharedRegion(name, (byte*)addr, size, null, null, addr, (nuint)size, posixOwner: true);
            }
            finally
            {
                // The mapping keeps the object alive; the descriptor is not needed past mmap.
                Posix.close(fd);
            }
        }

        private static SharedRegion OpenPosix(string name)
        {
            string posixName;
            try { posixName = PosixName(name); }
            catch (ArgumentException) { return null; }

            int fd = Posix.shm_open(posixName, Posix.O_RDONLY, 0);
            if (fd < 0) return null;

            try
            {
                if (Posix.fstat_size(fd, out long size) != 0 || size <= 0) return null;

                var addr = Posix.mmap(IntPtr.Zero, (nuint)size, Posix.PROT_READ, Posix.MAP_SHARED, fd, 0);
                if (addr == Posix.MAP_FAILED) return null;

                return new SharedRegion(name, (byte*)addr, size, null, null, addr, (nuint)size, posixOwner: false);
            }
            finally
            {
                Posix.close(fd);
            }
        }

        /// <summary>
        /// The POSIX shared-memory calls. Values differ between macOS and Linux for the open
        /// flags, which is the sort of thing that silently half-works if guessed — they are taken
        /// from each platform's <c>fcntl.h</c>.
        /// </summary>
        private static class Posix
        {
            public static readonly IntPtr MAP_FAILED = new IntPtr(-1);

            public const int O_RDONLY = 0x0000;
            public const int O_RDWR = 0x0002;

            public static readonly int O_CREAT = OperatingSystem.IsMacOS() ? 0x0200 : 0x0040;
            public static readonly int O_EXCL = OperatingSystem.IsMacOS() ? 0x0800 : 0x0080;

            public const int PROT_READ = 0x1;
            public const int PROT_WRITE = 0x2;
            public const int MAP_SHARED = 0x1;

            [DllImport("libc", SetLastError = true)]
            public static extern int shm_open([MarshalAs(UnmanagedType.LPUTF8Str)] string name, int oflag, uint mode);

            [DllImport("libc", SetLastError = true)]
            public static extern int shm_unlink([MarshalAs(UnmanagedType.LPUTF8Str)] string name);

            [DllImport("libc", SetLastError = true)]
            public static extern int ftruncate(int fd, long length);

            [DllImport("libc", SetLastError = true)]
            public static extern IntPtr mmap(IntPtr addr, nuint length, int prot, int flags, int fd, long offset);

            [DllImport("libc", SetLastError = true)]
            public static extern int munmap(IntPtr addr, nuint length);

            [DllImport("libc", SetLastError = true)]
            public static extern int close(int fd);

            /// <summary>
            /// The size of an open shm object. <c>fstat</c>'s struct layout is platform- and
            /// version-specific, so this seeks to the end instead — a portable question with a
            /// portable answer.
            /// </summary>
            public static int fstat_size(int fd, out long size)
            {
                size = lseek(fd, 0, SEEK_END);
                if (size < 0) return -1;
                return lseek(fd, 0, SEEK_SET) < 0 ? -1 : 0;
            }

            private const int SEEK_SET = 0;
            private const int SEEK_END = 2;

            [DllImport("libc", SetLastError = true)]
            private static extern long lseek(int fd, long offset, int whence);
        }
    }
}
